### ISSUE TITLE
Sending and receiving

### ISSUE THREAD

**Issue by scoson09** [LQR471814/FileTransfer#2]
Code:

import socket
import FileTransfer as ft

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)  
port = 56565        # Reserve a port for your service.
s.bind(("192.168.0.50", port))  

s.listen(5)   

c, addr = s.accept()  
rec = ft.receive("C:\Python36", c)
c.close()

Error:

rec = ft.receive("C:\Python36", c)
AttributeError: module 'FileTransfer' has no attribute 'receive'

Same thing happens with the client, I get an error saying AttributeError: module 'FileTransfer' has no attribute 'send'

**Comment by LQR471814** [comment]
Did you install the package? Do you have multiple versions of python installed?

**Comment by scoson09** [comment]
I do have multiple versions of python, I've just double-checked and it is installed into the correct version. I have the package installed on two computers as I'm trying to get a server and client working together, so I don't think the installation is the issue. I'm getting the receive error on one machine and the send error on another.

**Comment by LQR471814** [comment]
Alright I fixed it, you should go and update the package to v0.1.2.

Oh yeah, and watch out you no longer need to specify file destination.
